QtumApiService:
    Db:
        LogsConnString:
            settings-key: "QtumApiService-LogsConnString"
            types:
                - AzureBlobStorage
                - Tag

        DataConnString:
            settings-key: "QtumApiService-DataConnString"
            types:
                - AzureTableStorage      
                - Tag
FeeSettings:
    FeePerByte:
        settings-key: "QtumApiService-FeePerByte"
        types:
            - Tag
    MinFeeValueSatoshi:
        settings-key: "QtumApiService-MinFeeValueSatoshi"
        types:
            - Tag
    MaxFeeValueSatoshi:
        settings-key: "QtumApiService-MaxFeeValueSatoshi"
        types:
            - Tag
Network: 
    settings-key: "QtumApiService-Network"
    types:
        - Tag
ConfirmationsCount:
    settings-key: "QtumApiService-ConfirmationsCount"
    types:
        - Tag
ExternalApi:
    QtumInsightApi:
        settings-key: "QtumApiService-QtumInsightApi"
        types:
            - Tag
    DirectNodeApi:
        Url:
            settings-key: "QtumApiService-DirectNodeApiUrl"
            types:
                - Tag
        UserName:
            settings-key: "QtumApiService-DirectNodeApiUserName"
            types:
                - Tag
        Password:
            settings-key: "QtumApiService-DirectNodeApiPassword"
            types:
                - Tag
    
MonitoringServiceClient:
    MonitoringServiceUrl:
        settings-key: MonitoringServiceUrl  
  
SlackNotifications:
    AzureQueue:
        ConnectionString:
            settings-key: SlackNotificationsConnString
            types:
                - AzureTableStorage
        QueueName: 
            settings-key: SlackQueueName